safe: true
#url: https://www.humancomputation.com
url: https://hy-ng.github.io
exclude: [README.md, CNAME, LICENSE, util, Gemfile, Gemfile.lock, vendor, vendor-bundle]
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-minimal