safe: true
url: https://www.humancomputation2020test.com
exclude: [README.md, CNAME, LICENSE, util, Gemfile, Gemfile.lock, vendor, vendor-bundle]
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-minimal